### ISSUE TITLE
Add new inventory endpoint

### ISSUE THREAD

**Issue by igeligel** [igeligel/skadisteam.inventory#1]
Since steam has changed the way inventory API access is working we need to change it.

The old API listens on: http://steamcommunity.com/profiles/76561198045552709/inventory/json/730/2

The new one is here: http://steamcommunity.com/inventory/76561198045552709/570/2?l=english&count=5000

We could even add pagination but i believe this is unnecessary.

**Comment by igeligel** [comment]
Fixed with 1d23b4b3d903d0439e69a76b816ebe9f597efd7d

**Comment by shravan2x** [comment]
Why do we have a separate `SkadiItem` class? Is this the description information?

**Comment by igeligel** [comment]
For example some properties are not available like ``IconDragUrl`` or ``NameColor``. I also marked the old method as obsolete. Ill see to adjust the interface so it is reusable. Probably also move the models into the [shared project](https://github.com/igeligel/skadisteam.shared) so integrations will work better.
